version: '3'

services:
  worker1:
    hostname: worker1
    image: 'docker:${DOCKER_ENGINE_VERSION:-edge-dind}'
    privileged: true
    command: ['--insecure-registry=registry:5000', '--registry-mirror=http://registry-mirror:5000']
    labels:
      docker-kurs: "worker"

  worker2:
    hostname: worker2
    image: 'docker:${DOCKER_ENGINE_VERSION:-edge-dind}'
    privileged: true
    command: ['--insecure-registry=registry:5000', '--registry-mirror=http://registry-mirror:5000']
    labels:
      docker-kurs: "worker"
      
   worker3:
    hostname: worker3
    image: 'docker:${DOCKER_ENGINE_VERSION:-edge-dind}'
    privileged: true
    command: ['--insecure-registry=registry:5000', '--registry-mirror=http://registry-mirror:5000']
    labels:
      docker-kurs: "worker"
      
  registry:
    image: 'registry:2'
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    restart: on-failure

  registry-mirror:
    image: 'registry:2'
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    volumes:
      - registry-mirror-data:/var/lib/registry
    restart: on-failure
volumes:
  registry-data:
  registry-mirror-data:
